## Loading The Data

In [11]:
import pandas as pd
import numpy as np
from pathlib import Path

In [12]:
RAW_DIR = Path("../data/raw")
PROCESSED_DIR = Path("../data/processed")

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [13]:
for file in RAW_DIR.iterdir():
    print(file.name)

11100065-eng
11100065.csv
36100226-eng
36100226.csv
38100235-eng
38100235.csv
insolvency_monthly.xlsx

In [15]:
df_11100065 = pd.read_csv(RAW_DIR / "11100065.csv")
df_38100235 = pd.read_csv(RAW_DIR / "38100235.csv")
df_36100226 = pd.read_csv(RAW_DIR / "36100226.csv")

In [16]:
print("Table 11-10-0065-01")
print(df_11100065.shape)
display(df_11100065.head())
print(df_11100065.columns.tolist())

Table 11-10-0065-01
(8352, 16)

,REF_DATE,GEO,DGUID,Seasonal adjustment,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1990-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Household income,Dollars,81,millions,6,v1001696792,1.1.1,615496.0,NaN,NaN,NaN,0
1,1990-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Compensation of employees,Dollars,81,millions,6,v1001696793,1.1.2,364088.0,NaN,NaN,NaN,0
2,1990-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Net mixed income,Dollars,81,millions,6,v1001696794,1.1.3,68496.0,NaN,NaN,NaN,0
3,1990-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Property income received,Dollars,81,millions,6,v1001696795,1.1.4,102048.0,NaN,NaN,NaN,0
4,1990-01,Canada,2016A000011124,Seasonally adjusted at annual rates,Current transfers received,Dollars,81,millions,6,v1001696796,1.1.5,80864.0,NaN,NaN,NaN,0

['REF_DATE', 'GEO', 'DGUID', 'Seasonal adjustment', 'Estimates', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']

In [17]:
print("Table 38-10-0235-01")
print(df_38100235.shape)
display(df_38100235.head())
print(df_38100235.columns.tolist())

Table 38-10-0235-01
(2880, 16)

,REF_DATE,GEO,DGUID,Sectors,Categories,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1990-01,Canada,2021A000011124,Households,Debt to gross domestic product (GDP),Percent,239,units,0,v62698062,1.1.1,54.02,NaN,NaN,NaN,2
1,1990-01,Canada,2021A000011124,Households,Debt to disposable income,Percent,239,units,0,v62698063,1.1.2,87.97,NaN,NaN,NaN,2
2,1990-01,Canada,2021A000011124,Households,Credit market debt to disposable income,Percent,239,units,0,v62698064,1.1.3,86.11,NaN,NaN,NaN,2
3,1990-01,Canada,2021A000011124,Households,Consumer credit and mortgage liabilities to di...,Percent,239,units,0,v62698065,1.1.4,78.86,NaN,NaN,NaN,2
4,1990-01,Canada,2021A000011124,Households,Net worth as a percentage of disposable income,Percent,239,units,0,v62698066,1.1.5,512.14,NaN,NaN,NaN,2

['REF_DATE', 'GEO', 'DGUID', 'Sectors', 'Categories', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']

In [18]:
print("Table 36-10-0226-01")
print(df_36100226.shape)
display(df_36100226.head())
print(df_36100226.columns.tolist())

Table 36-10-0226-01
(9370, 15)

,REF_DATE,GEO,DGUID,Estimates,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,1981,Canada,2016A000011124,Household income,Dollars,81,millions,6,v62790675,1.1,311698.0,NaN,NaN,NaN,0
1,1981,Canada,2016A000011124,Compensation of employees,Dollars,81,millions,6,v62790676,1.2,196616.0,NaN,NaN,NaN,0
2,1981,Canada,2016A000011124,Net mixed income,Dollars,81,millions,6,v62790677,1.3,34442.0,NaN,NaN,NaN,0
3,1981,Canada,2016A000011124,Property income received,Dollars,81,millions,6,v62790678,1.4,48250.0,NaN,NaN,NaN,0
4,1981,Canada,2016A000011124,Current transfers received,Dollars,81,millions,6,v62790679,1.5,32390.0,NaN,NaN,NaN,0

['REF_DATE', 'GEO', 'DGUID', 'Estimates', 'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']

In [19]:
insolvency_path = RAW_DIR / "insolvency_monthly.xlsx"

xls = pd.ExcelFile(insolvency_path)
xls.sheet_names

['Monthly_mensuels']

In [20]:
for sheet in xls.sheet_names:
    temp = pd.read_excel(insolvency_path, sheet_name=sheet, nrows=5)
    print("\nSheet:", sheet)
    display(temp)

Sheet: Monthly_mensuels

,Insolvency Statistics/Statistiques sur l'insolvabilité 1987-2025,Unnamed: 1,Jan/janv 1987,Feb/fév 1987,Mar 1987,Apr/avr 1987,May/mai 1987,Jun/juin 1987,Jul/juil 1987,Aug/août 1987,...,Jun/juin 2025,Jul/juill 2025,Aug/août 2025,Sep/Sept 2025,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,Jan/janv 2026,Feb/fév 2026,2026-03-01 00:00:00
0,Canada/Canada,Total Insolvencies/Nombre total de dossiers d'...,2765,2896,2996,2720,2529,2922,2487,2582,...,11883,12661,11631,13072,13091,11904,10989,11775,12715,13863
1,NaN,Total Bankruptcies/Nombre total de faillites,2722,2861,2928,2683,2492,2880,2455,2544,...,2856,2897,2644,3087,3052,2757,2770,2637,2799,3083
2,NaN,Total Proposals/Nombre total de propositions,43,35,68,37,37,42,32,38,...,9027,9764,8987,9985,10039,9147,8219,9138,9916,10780
3,NaN,Consumer Insolvencies/Insolvabilité des c...,2060,2185,2245,2071,1884,2209,1912,1991,...,11464,12285,11303,12668,12662,11548,10652,11408,12307,13406
4,NaN,Consumer Bankruptcies/Faillites des conso...,2037,2162,2202,2046,1866,2180,1890,1962,...,2529,2611,2383,2793,2724,2484,2510,2349,2479,2748

## Standardize Column Names

In [28]:

def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.replace("/", "_")
    )
    return df


df_111 = clean_column_names(df_11100065)
df_381 = clean_column_names(df_38100235)
df_361 = clean_column_names(df_36100226)

print(df_111.columns.tolist())
print(df_381.columns.tolist())
print(df_361.columns.tolist())

['ref_date', 'geo', 'dguid', 'seasonal_adjustment', 'estimates', 'uom', 'uom_id', 'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated', 'decimals']
['ref_date', 'geo', 'dguid', 'sectors', 'categories', 'uom', 'uom_id', 'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated', 'decimals']
['ref_date', 'geo', 'dguid', 'estimates', 'uom', 'uom_id', 'scalar_factor', 'scalar_id', 'vector', 'coordinate', 'value', 'status', 'symbol', 'terminated', 'decimals']

In [29]:
statcan_111_long = df_111[
    [
        "ref_date",
        "geo",
        "estimates",
        "uom",
        "value"
    ]
].copy()

statcan_111_long = statcan_111_long.rename(
    columns={
        "ref_date": "date",
        "geo": "geography",
        "estimates": "indicator_name",
        "uom": "unit"
    }
)

statcan_111_long["source"] = "Statistics Canada Table 11-10-0065-01"
statcan_111_long["frequency"] = "Monthly/Quarterly"

statcan_111_long.head()

,date,geography,indicator_name,unit,value,source,frequency
0,1990-01,Canada,Household income,Dollars,615496.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
1,1990-01,Canada,Compensation of employees,Dollars,364088.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
2,1990-01,Canada,Net mixed income,Dollars,68496.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
3,1990-01,Canada,Property income received,Dollars,102048.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
4,1990-01,Canada,Current transfers received,Dollars,80864.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly

In [30]:
statcan_381_long = df_381[
    [
        "ref_date",
        "geo",
        "sectors",
        "categories",
        "uom",
        "value"
    ]
].copy()

statcan_381_long = statcan_381_long.rename(
    columns={
        "ref_date": "date",
        "geo": "geography",
        "categories": "indicator_name",
        "uom": "unit"
    }
)

statcan_381_long["source"] = "Statistics Canada Table 38-10-0235-01"
statcan_381_long["frequency"] = "Monthly/Quarterly"

statcan_381_long = statcan_381_long[
    [
        "date",
        "geography",
        "indicator_name",
        "value",
        "unit",
        "frequency",
        "source"
    ]
]

statcan_381_long.head()

,date,geography,indicator_name,value,unit,frequency,source
0,1990-01,Canada,Debt to gross domestic product (GDP),54.02,Percent,Monthly/Quarterly,Statistics Canada Table 38-10-0235-01
1,1990-01,Canada,Debt to disposable income,87.97,Percent,Monthly/Quarterly,Statistics Canada Table 38-10-0235-01
2,1990-01,Canada,Credit market debt to disposable income,86.11,Percent,Monthly/Quarterly,Statistics Canada Table 38-10-0235-01
3,1990-01,Canada,Consumer credit and mortgage liabilities to di...,78.86,Percent,Monthly/Quarterly,Statistics Canada Table 38-10-0235-01
4,1990-01,Canada,Net worth as a percentage of disposable income,512.14,Percent,Monthly/Quarterly,Statistics Canada Table 38-10-0235-01

In [31]:
statcan_361_long = df_361[
    [
        "ref_date",
        "geo",
        "estimates",
        "uom",
        "value"
    ]
].copy()

statcan_361_long = statcan_361_long.rename(
    columns={
        "ref_date": "date",
        "geo": "geography",
        "estimates": "indicator_name",
        "uom": "unit"
    }
)

statcan_361_long["source"] = "Statistics Canada Table 36-10-0226-01"
statcan_361_long["frequency"] = "Annual"

statcan_361_long.head()

,date,geography,indicator_name,unit,value,source,frequency
0,1981,Canada,Household income,Dollars,311698.0,Statistics Canada Table 36-10-0226-01,Annual
1,1981,Canada,Compensation of employees,Dollars,196616.0,Statistics Canada Table 36-10-0226-01,Annual
2,1981,Canada,Net mixed income,Dollars,34442.0,Statistics Canada Table 36-10-0226-01,Annual
3,1981,Canada,Property income received,Dollars,48250.0,Statistics Canada Table 36-10-0226-01,Annual
4,1981,Canada,Current transfers received,Dollars,32390.0,Statistics Canada Table 36-10-0226-01,Annual

## Filter Relevant Risk Indicators

In [34]:
for name, df in {
    "11100065": statcan_111_long,
    "38100235": statcan_381_long,
    "36100226": statcan_361_long
}.items():
    print("\n","="*50)
    print(name)
    print("="*50)
    
    for indicator in sorted(df["indicator_name"].dropna().unique()):
        if any(keyword in indicator.lower() for keyword in 
               ["debt", "income", "service", "liabilities", "credit", "interest"]):
            print(indicator)

 ==================================================
11100065
==================================================
Debt service ratio
Debt service ratio, interest only
Disposable income
Equals: disposable income before payment of interest
Household income
Mortgage debt payments
Mortgage debt service ratio
Mortgage debt service ratio, interest only
Mortgage interest paid
Net mixed income
Non-mortgage debt payments
Non-mortgage debt service ratio
Non-mortgage debt service ratio, interest only
Non-mortgage interest paid
Of which: consumer debt
Of which: consumer debt service ratio, interest only
Plus: Interest paid
Property income paid
Property income received
Total debt payments
Total interest paid

 ==================================================
38100235
==================================================
Consumer credit and mortgage liabilities to disposable income
Consumer credit and mortgage liabilities to net worth
Credit market debt to disposable income
Credit market debt to net worth
Debt to disposable income
Debt to gross domestic product (GDP)
Debt to net worth
Debt to total assets
Effective interest cost, mortgage loans (unadjusted at quarterly rates)
Effective interest cost, non-mortgage loans (unadjusted at quarterly rates)
Effective interest cost, total loans (unadjusted at quarterly rates)
Net worth as a percentage of disposable income
Real estate as a percentage of disposable income

 ==================================================
36100226
==================================================
Divided by: household disposable income
Equals: debt service ratio, interest only
Household income
Interest paid
Mortgage interest paid
Net mixed income
Non-mortgage interest paid
Property income paid
Property income received

In [37]:
selected_indicators_111 = [
    "Debt service ratio",
    "Debt service ratio, interest only",
    "Mortgage debt payments",
    "Mortgage debt service ratio",
    "Mortgage debt service ratio, interest only",
    "Mortgage interest paid",
    "Non-mortgage debt payments",
    "Non-mortgage debt service ratio",
    "Non-mortgage debt service ratio, interest only",
    "Non-mortgage interest paid",
    "Of which: consumer debt ",
    "Of which: consumer debt service ratio, interest only",
    "Plus: Interest paid",
    "Total debt payments",
    "Total interest paid",
    "Disposable income ",
    "Household income"
]

selected_indicators_381 = [
    "Debt to disposable income",
    "Credit market debt to disposable income",
    "Consumer credit and mortgage liabilities to disposable income",
    "Debt to gross domestic product (GDP)",
    "Debt to net worth",
    "Debt to total assets",
    "Consumer credit and mortgage liabilities to net worth",
    "Credit market debt to net worth",
    "Effective interest cost, total loans (unadjusted at quarterly rates)",
    "Effective interest cost, mortgage loans (unadjusted at quarterly rates)",
    "Effective interest cost, non-mortgage loans (unadjusted at quarterly rates)"
]

selected_indicators_361 = [
    "Divided by: household disposable income",
    "Equals: debt service ratio, interest only",
    "Household income",
    "Interest paid",
    "Mortgage interest paid",
    "Non-mortgage interest paid"
]

In [38]:
risk_111 = statcan_111_long[
    statcan_111_long["indicator_name"].isin(selected_indicators_111)
].copy()

risk_381 = statcan_381_long[
    statcan_381_long["indicator_name"].isin(selected_indicators_381)
].copy()

risk_361 = statcan_361_long[
    statcan_361_long["indicator_name"].isin(selected_indicators_361)
].copy()

## Combine Selected StatCan Indicators

In [40]:
master_statcan = pd.concat(
    [
        risk_111,
        risk_381,
        risk_361
    ],
    ignore_index=True
)

master_statcan["value"] = pd.to_numeric(master_statcan["value"], errors="coerce")

master_statcan.head()

,date,geography,indicator_name,unit,value,source,frequency
0,1990-01,Canada,Household income,Dollars,615496.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
1,1990-01,Canada,Disposable income,Dollars,403280.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
2,1990-01,Canada,Plus: Interest paid,Dollars,47900.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
3,1990-01,Canada,Total debt payments,Dollars,55000.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly
4,1990-01,Canada,Mortgage debt payments,Dollars,29148.0,Statistics Canada Table 11-10-0065-01,Monthly/Quarterly

In [41]:
master_statcan.to_csv(
    PROCESSED_DIR / "master_statcan_credit_risk_indicators.csv",
    index=False
)

In [42]:
debt_service = risk_111.copy()

debt_service["date"] = pd.to_datetime(debt_service["date"], errors="coerce")
debt_service["value"] = pd.to_numeric(debt_service["value"], errors="coerce")

debt_service_wide = debt_service.pivot_table(
    index=["date", "geography"],
    columns="indicator_name",
    values="value",
    aggfunc="first"
).reset_index()

debt_service_wide.columns.name = None

debt_service_wide = debt_service_wide.rename(
    columns={
        "Debt service ratio": "debt_service_ratio",
        "Debt service ratio, interest only": "debt_service_ratio_interest_only",
        "Mortgage debt payments": "mortgage_debt_payments",
        "Mortgage debt service ratio": "mortgage_debt_service_ratio",
        "Mortgage debt service ratio, interest only": "mortgage_debt_service_ratio_interest_only",
        "Mortgage interest paid": "mortgage_interest_paid",
        "Non-mortgage debt payments": "non_mortgage_debt_payments",
        "Non-mortgage debt service ratio": "non_mortgage_debt_service_ratio",
        "Non-mortgage debt service ratio, interest only": "non_mortgage_debt_service_ratio_interest_only",
        "Non-mortgage interest paid": "non_mortgage_interest_paid",
        "Of which: consumer debt ": "consumer_debt",
        "Of which: consumer debt service ratio, interest only": "consumer_debt_service_ratio_interest_only",
        "Plus: Interest paid": "interest_paid",
        "Total debt payments": "total_debt_payments",
        "Total interest paid": "total_interest_paid",
        "Disposable income ": "disposable_income",
        "Household income": "household_income"
    }
)

debt_service_wide.head()

,date,geography,debt_service_ratio,debt_service_ratio_interest_only,disposable_income,household_income,mortgage_debt_payments,mortgage_debt_service_ratio,mortgage_debt_service_ratio_interest_only,mortgage_interest_paid,non_mortgage_debt_payments,non_mortgage_debt_service_ratio,non_mortgage_debt_service_ratio_interest_only,non_mortgage_interest_paid,consumer_debt,consumer_debt_service_ratio_interest_only,interest_paid,total_debt_payments,total_interest_paid
0,1990-01-01,Canada,12.19,10.62,403280.0,615496.0,29148.0,6.46,6.04,27248.0,25852.0,5.73,4.58,20652.0,16024.0,3.55,47900.0,55000.0,47900.0
1,1990-04-01,Canada,12.68,11.16,392652.0,626452.0,29564.0,6.69,6.31,27888.0,26468.0,5.99,4.85,21428.0,16732.0,3.79,49316.0,56032.0,49316.0
2,1990-07-01,Canada,12.47,11.08,404988.0,631908.0,30152.0,6.62,6.25,28464.0,26640.0,5.85,4.83,22020.0,17300.0,3.80,50484.0,56792.0,50484.0
3,1990-10-01,Canada,12.29,11.04,412232.0,638984.0,30748.0,6.64,6.26,29020.0,26208.0,5.66,4.78,22128.0,17504.0,3.78,51148.0,56956.0,51148.0
4,1991-01-01,Canada,12.19,10.98,417232.0,640844.0,31884.0,6.80,6.42,30108.0,25252.0,5.39,4.56,21380.0,17092.0,3.65,51488.0,57136.0,51488.0

In [43]:
debt_income = risk_381.copy()

debt_income["date"] = pd.to_datetime(debt_income["date"], errors="coerce")
debt_income["value"] = pd.to_numeric(debt_income["value"], errors="coerce")

debt_income_wide = debt_income.pivot_table(
    index=["date", "geography"],
    columns="indicator_name",
    values="value",
    aggfunc="first"
).reset_index()

debt_income_wide.columns.name = None

debt_income_wide = debt_income_wide.rename(
    columns={
        "Debt to disposable income": "debt_to_disposable_income",
        "Credit market debt to disposable income": "credit_market_debt_to_disposable_income",
        "Consumer credit and mortgage liabilities to disposable income": "consumer_credit_mortgage_liabilities_to_income",
        "Debt to gross domestic product (GDP)": "debt_to_gdp",
        "Debt to net worth": "debt_to_net_worth",
        "Debt to total assets": "debt_to_total_assets",
        "Consumer credit and mortgage liabilities to net worth": "consumer_credit_mortgage_liabilities_to_net_worth",
        "Credit market debt to net worth": "credit_market_debt_to_net_worth",
        "Effective interest cost, total loans (unadjusted at quarterly rates)": "effective_interest_cost_total_loans",
        "Effective interest cost, mortgage loans (unadjusted at quarterly rates)": "effective_interest_cost_mortgage_loans",
        "Effective interest cost, non-mortgage loans (unadjusted at quarterly rates)": "effective_interest_cost_non_mortgage_loans"
    }
)

debt_income_wide.head()

,date,geography,consumer_credit_mortgage_liabilities_to_income,consumer_credit_mortgage_liabilities_to_net_worth,credit_market_debt_to_disposable_income,credit_market_debt_to_net_worth,debt_to_disposable_income,debt_to_gdp,debt_to_net_worth,debt_to_total_assets,effective_interest_cost_mortgage_loans,effective_interest_cost_non_mortgage_loans,effective_interest_cost_total_loans
0,1990-01-01,Canada,78.86,15.40,86.11,16.81,87.97,54.02,17.18,14.66,2.83,4.21,3.30
1,1990-04-01,Canada,80.66,16.03,87.86,17.46,90.04,55.01,17.90,15.18,2.81,4.25,3.29
2,1990-07-01,Canada,80.89,16.15,88.01,17.58,90.33,55.59,18.04,15.28,2.87,4.41,3.39
3,1990-10-01,Canada,81.24,16.16,88.29,17.56,90.52,56.23,18.01,15.26,2.91,4.41,3.41
4,1991-01-01,Canada,81.06,15.80,88.00,17.15,90.05,56.45,17.55,14.93,2.88,4.23,3.32

## Merge Debt Service + Debt-to-Income

In [44]:
dashboard_canada = debt_service_wide.merge(
    debt_income_wide,
    on=["date", "geography"],
    how="outer"
)

dashboard_canada = dashboard_canada.sort_values(["geography", "date"])

dashboard_canada.head()

,date,geography,debt_service_ratio,debt_service_ratio_interest_only,disposable_income,household_income,mortgage_debt_payments,mortgage_debt_service_ratio,mortgage_debt_service_ratio_interest_only,mortgage_interest_paid,...,consumer_credit_mortgage_liabilities_to_net_worth,credit_market_debt_to_disposable_income,credit_market_debt_to_net_worth,debt_to_disposable_income,debt_to_gdp,debt_to_net_worth,debt_to_total_assets,effective_interest_cost_mortgage_loans,effective_interest_cost_non_mortgage_loans,effective_interest_cost_total_loans
0,1990-01-01,Canada,12.19,10.62,403280.0,615496.0,29148.0,6.46,6.04,27248.0,...,15.40,86.11,16.81,87.97,54.02,17.18,14.66,2.83,4.21,3.30
1,1990-04-01,Canada,12.68,11.16,392652.0,626452.0,29564.0,6.69,6.31,27888.0,...,16.03,87.86,17.46,90.04,55.01,17.90,15.18,2.81,4.25,3.29
2,1990-07-01,Canada,12.47,11.08,404988.0,631908.0,30152.0,6.62,6.25,28464.0,...,16.15,88.01,17.58,90.33,55.59,18.04,15.28,2.87,4.41,3.39
3,1990-10-01,Canada,12.29,11.04,412232.0,638984.0,30748.0,6.64,6.26,29020.0,...,16.16,88.29,17.56,90.52,56.23,18.01,15.26,2.91,4.41,3.41
4,1991-01-01,Canada,12.19,10.98,417232.0,640844.0,31884.0,6.80,6.42,30108.0,...,15.80,88.00,17.15,90.05,56.45,17.55,14.93,2.88,4.23,3.32

In [45]:
dashboard_canada.columns.tolist()

['date',
 'geography',
 'debt_service_ratio',
 'debt_service_ratio_interest_only',
 'disposable_income',
 'household_income',
 'mortgage_debt_payments',
 'mortgage_debt_service_ratio',
 'mortgage_debt_service_ratio_interest_only',
 'mortgage_interest_paid',
 'non_mortgage_debt_payments',
 'non_mortgage_debt_service_ratio',
 'non_mortgage_debt_service_ratio_interest_only',
 'non_mortgage_interest_paid',
 'consumer_debt',
 'consumer_debt_service_ratio_interest_only',
 'interest_paid',
 'total_debt_payments',
 'total_interest_paid',
 'consumer_credit_mortgage_liabilities_to_income',
 'consumer_credit_mortgage_liabilities_to_net_worth',
 'credit_market_debt_to_disposable_income',
 'credit_market_debt_to_net_worth',
 'debt_to_disposable_income',
 'debt_to_gdp',
 'debt_to_net_worth',
 'debt_to_total_assets',
 'effective_interest_cost_mortgage_loans',
 'effective_interest_cost_non_mortgage_loans',
 'effective_interest_cost_total_loans']

In [46]:
dashboard_canada["disposable_income_growth_yoy"] = dashboard_canada.groupby(
    "geography"
)["disposable_income"].pct_change(4) * 100

dashboard_canada["debt_to_income_change_yoy"] = dashboard_canada.groupby(
    "geography"
)["debt_to_disposable_income"].diff(4)

dashboard_canada["debt_service_ratio_change_yoy"] = dashboard_canada.groupby(
    "geography"
)["debt_service_ratio"].diff(4)

dashboard_canada["interest_cost_change_yoy"] = dashboard_canada.groupby(
    "geography"
)["effective_interest_cost_total_loans"].diff(4)

In [48]:
dashboard_canada.head()

,date,geography,debt_service_ratio,debt_service_ratio_interest_only,disposable_income,household_income,mortgage_debt_payments,mortgage_debt_service_ratio,mortgage_debt_service_ratio_interest_only,mortgage_interest_paid,...,debt_to_gdp,debt_to_net_worth,debt_to_total_assets,effective_interest_cost_mortgage_loans,effective_interest_cost_non_mortgage_loans,effective_interest_cost_total_loans,disposable_income_growth_yoy,debt_to_income_change_yoy,debt_service_ratio_change_yoy,interest_cost_change_yoy
0,1990-01-01,Canada,12.19,10.62,403280.0,615496.0,29148.0,6.46,6.04,27248.0,...,54.02,17.18,14.66,2.83,4.21,3.30,NaN,NaN,NaN,NaN
1,1990-04-01,Canada,12.68,11.16,392652.0,626452.0,29564.0,6.69,6.31,27888.0,...,55.01,17.90,15.18,2.81,4.25,3.29,NaN,NaN,NaN,NaN
2,1990-07-01,Canada,12.47,11.08,404988.0,631908.0,30152.0,6.62,6.25,28464.0,...,55.59,18.04,15.28,2.87,4.41,3.39,NaN,NaN,NaN,NaN
3,1990-10-01,Canada,12.29,11.04,412232.0,638984.0,30748.0,6.64,6.26,29020.0,...,56.23,18.01,15.26,2.91,4.41,3.41,NaN,NaN,NaN,NaN
4,1991-01-01,Canada,12.19,10.98,417232.0,640844.0,31884.0,6.80,6.42,30108.0,...,56.45,17.55,14.93,2.88,4.23,3.32,3.459631,2.08,0.0,0.02

In [49]:
def score_debt_service_ratio(x):
    if pd.isna(x):
        return np.nan
    if x < 13:
        return 20
    elif x < 14:
        return 45
    elif x < 15:
        return 65
    else:
        return 85


def score_debt_to_income(x):
    if pd.isna(x):
        return np.nan
    if x < 160:
        return 20
    elif x < 175:
        return 45
    elif x < 185:
        return 65
    else:
        return 85


def score_interest_pressure(x):
    if pd.isna(x):
        return np.nan
    if x < 0:
        return 20
    elif x < 0.25:
        return 45
    elif x < 0.75:
        return 65
    else:
        return 85


def score_income_pressure(x):
    if pd.isna(x):
        return np.nan
    if x > 5:
        return 20
    elif x > 2:
        return 45
    elif x > 0:
        return 65
    else:
        return 85

In [50]:
dashboard_canada["dsr_score"] = dashboard_canada["debt_service_ratio"].apply(
    score_debt_service_ratio
)

dashboard_canada["debt_income_score"] = dashboard_canada["debt_to_disposable_income"].apply(
    score_debt_to_income
)

dashboard_canada["interest_pressure_score"] = dashboard_canada["interest_cost_change_yoy"].apply(
    score_interest_pressure
)

dashboard_canada["income_pressure_score"] = dashboard_canada["disposable_income_growth_yoy"].apply(
    score_income_pressure
)

## Risk Score Weighting Methodology

The risk score uses **analyst-defined heuristic weights**. These are not official regulatory, Bank of Canada, or Statistics Canada weights. They are created for this project to turn multiple household credit-risk indicators into one simple monitoring score.

The purpose of the score is not to predict individual borrower default. The purpose is to help a risk analyst or risk manager quickly understand whether household credit conditions are becoming more stressed over time.

```python
risk_score =
    debt_service_ratio_score * 0.35 +
    debt_income_score * 0.30 +
    interest_pressure_score * 0.20 +
    income_pressure_score * 0.15

In [51]:
dashboard_canada["risk_score"] = (
    dashboard_canada["dsr_score"] * 0.35 +
    dashboard_canada["debt_income_score"] * 0.30 +
    dashboard_canada["interest_pressure_score"] * 0.20 +
    dashboard_canada["income_pressure_score"] * 0.15
)

In [52]:
def assign_risk_category(score):
    if pd.isna(score):
        return "Insufficient Data"
    if score < 40:
        return "Low Risk"
    elif score < 60:
        return "Moderate Risk"
    elif score < 75:
        return "Elevated Risk"
    else:
        return "High Risk"


dashboard_canada["risk_category"] = dashboard_canada["risk_score"].apply(
    assign_risk_category
)

In [53]:
def assign_suggested_action(category):
    if category == "Low Risk":
        return "Continue standard monitoring"
    elif category == "Moderate Risk":
        return "Increase monitoring of household credit stress indicators"
    elif category == "Elevated Risk":
        return "Review vulnerable borrower segments and stress-test portfolios"
    elif category == "High Risk":
        return "Escalate to risk committee and review credit policy thresholds"
    else:
        return "Data review required"


dashboard_canada["suggested_action"] = dashboard_canada["risk_category"].apply(
    assign_suggested_action
)

In [54]:
dashboard_canada.to_csv(
    PROCESSED_DIR / "dashboard_ready_canada_credit_risk_base.csv",
    index=False
)

In [56]:
dashboard_canada[
    dashboard_canada["risk_score"].notna()
].tail(10)[
    [
        "date",
        "geography",
        "debt_service_ratio",
        "debt_to_disposable_income",
        "disposable_income_growth_yoy",
        "interest_cost_change_yoy",
        "risk_score",
        "risk_category",
        "suggested_action"
    ]
].to_clipboard()

In [57]:
print(dashboard_canada.shape)
print(dashboard_canada["date"].min())
print(dashboard_canada["date"].max())
print(dashboard_canada["geography"].unique())

(144, 41)
1990-01-01 00:00:00
2025-10-01 00:00:00
['Canada']

## Clean Insolvency Data

In [58]:
insolvency_path = RAW_DIR / "insolvency_monthly.xlsx"

insolvency_df = pd.read_excel(insolvency_path)

insolvency_df.head()

,Insolvency Statistics/Statistiques sur l'insolvabilité 1987-2025,Unnamed: 1,Jan/janv 1987,Feb/fév 1987,Mar 1987,Apr/avr 1987,May/mai 1987,Jun/juin 1987,Jul/juil 1987,Aug/août 1987,...,Jun/juin 2025,Jul/juill 2025,Aug/août 2025,Sep/Sept 2025,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,Jan/janv 2026,Feb/fév 2026,2026-03-01 00:00:00
0,Canada/Canada,Total Insolvencies/Nombre total de dossiers d'...,2765.0,2896.0,2996.0,2720.0,2529.0,2922.0,2487.0,2582.0,...,11883,12661,11631,13072,13091,11904,10989,11775,12715,13863
1,NaN,Total Bankruptcies/Nombre total de faillites,2722.0,2861.0,2928.0,2683.0,2492.0,2880.0,2455.0,2544.0,...,2856,2897,2644,3087,3052,2757,2770,2637,2799,3083
2,NaN,Total Proposals/Nombre total de propositions,43.0,35.0,68.0,37.0,37.0,42.0,32.0,38.0,...,9027,9764,8987,9985,10039,9147,8219,9138,9916,10780
3,NaN,Consumer Insolvencies/Insolvabilité des c...,2060.0,2185.0,2245.0,2071.0,1884.0,2209.0,1912.0,1991.0,...,11464,12285,11303,12668,12662,11548,10652,11408,12307,13406
4,NaN,Consumer Bankruptcies/Faillites des conso...,2037.0,2162.0,2202.0,2046.0,1866.0,2180.0,1890.0,1962.0,...,2529,2611,2383,2793,2724,2484,2510,2349,2479,2748

In [59]:
insolvency_df.iloc[:10, :5]

,Insolvency Statistics/Statistiques sur l'insolvabilité 1987-2025,Unnamed: 1,Jan/janv 1987,Feb/fév 1987,Mar 1987
0,Canada/Canada,Total Insolvencies/Nombre total de dossiers d'...,2765.0,2896.0,2996.0
1,NaN,Total Bankruptcies/Nombre total de faillites,2722.0,2861.0,2928.0
2,NaN,Total Proposals/Nombre total de propositions,43.0,35.0,68.0
3,NaN,Consumer Insolvencies/Insolvabilité des c...,2060.0,2185.0,2245.0
4,NaN,Consumer Bankruptcies/Faillites des conso...,2037.0,2162.0,2202.0
5,NaN,Consumer Proposals/Propositions des conso...,23.0,23.0,43.0
6,NaN,Business Insolvencies/Insolvabilité des e...,705.0,711.0,751.0
7,NaN,Business Bankruptcies/Faillites des entre...,685.0,699.0,726.0
8,NaN,Business Proposals/Propositions des entre...,20.0,12.0,25.0
9,NaN,Corporate Insolvencies/Insolvabilité...,190.0,187.0,188.0

In [60]:
insolvency_clean = insolvency_df.copy()

insolvency_clean = insolvency_clean.rename(
    columns={
        insolvency_clean.columns[0]: "geography",
        insolvency_clean.columns[1]: "indicator_name"
    }
)

insolvency_clean.head()

,geography,indicator_name,Jan/janv 1987,Feb/fév 1987,Mar 1987,Apr/avr 1987,May/mai 1987,Jun/juin 1987,Jul/juil 1987,Aug/août 1987,...,Jun/juin 2025,Jul/juill 2025,Aug/août 2025,Sep/Sept 2025,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,Jan/janv 2026,Feb/fév 2026,2026-03-01 00:00:00
0,Canada/Canada,Total Insolvencies/Nombre total de dossiers d'...,2765.0,2896.0,2996.0,2720.0,2529.0,2922.0,2487.0,2582.0,...,11883,12661,11631,13072,13091,11904,10989,11775,12715,13863
1,NaN,Total Bankruptcies/Nombre total de faillites,2722.0,2861.0,2928.0,2683.0,2492.0,2880.0,2455.0,2544.0,...,2856,2897,2644,3087,3052,2757,2770,2637,2799,3083
2,NaN,Total Proposals/Nombre total de propositions,43.0,35.0,68.0,37.0,37.0,42.0,32.0,38.0,...,9027,9764,8987,9985,10039,9147,8219,9138,9916,10780
3,NaN,Consumer Insolvencies/Insolvabilité des c...,2060.0,2185.0,2245.0,2071.0,1884.0,2209.0,1912.0,1991.0,...,11464,12285,11303,12668,12662,11548,10652,11408,12307,13406
4,NaN,Consumer Bankruptcies/Faillites des conso...,2037.0,2162.0,2202.0,2046.0,1866.0,2180.0,1890.0,1962.0,...,2529,2611,2383,2793,2724,2484,2510,2349,2479,2748

In [61]:
insolvency_clean["geography"] = insolvency_clean["geography"].ffill()

In [62]:
insolvency_clean = insolvency_clean[
    insolvency_clean["indicator_name"].notna()
].copy()

## Pivoting Data

In [63]:
id_cols = ["geography", "indicator_name"]

date_cols = [col for col in insolvency_clean.columns if col not in id_cols]

insolvency_long = insolvency_clean.melt(
    id_vars=id_cols,
    value_vars=date_cols,
    var_name="date",
    value_name="value"
)

insolvency_long.head()

,geography,indicator_name,date,value
0,Canada/Canada,Total Insolvencies/Nombre total de dossiers d'...,Jan/janv 1987,2765.0
1,Canada/Canada,Total Bankruptcies/Nombre total de faillites,Jan/janv 1987,2722.0
2,Canada/Canada,Total Proposals/Nombre total de propositions,Jan/janv 1987,43.0
3,Canada/Canada,Consumer Insolvencies/Insolvabilité des c...,Jan/janv 1987,2060.0
4,Canada/Canada,Consumer Bankruptcies/Faillites des conso...,Jan/janv 1987,2037.0

In [65]:
insolvency_long["geography"] = (
    insolvency_long["geography"]
    .astype(str)
    .str.split("/")
    .str[0]
    .str.strip()
)

insolvency_long["indicator_name"] = (
    insolvency_long["indicator_name"]
    .astype(str)
    .str.split("/")
    .str[0]
    .str.strip()
)

insolvency_long.head()

  geography         indicator_name           date   value
0    Canada     Total Insolvencies  Jan/janv 1987  2765.0
1    Canada     Total Bankruptcies  Jan/janv 1987  2722.0
2    Canada        Total Proposals  Jan/janv 1987    43.0
3    Canada  Consumer Insolvencies  Jan/janv 1987  2060.0
4    Canada  Consumer Bankruptcies  Jan/janv 1987  2037.0

In [66]:
insolvency_long["indicator_name"].drop_duplicates().head(20)

0                   Total Insolvencies
1                   Total Bankruptcies
2                      Total Proposals
3                Consumer Insolvencies
4                Consumer Bankruptcies
5                   Consumer Proposals
6                Business Insolvencies
7                Business Bankruptcies
8                   Business Proposals
9               Corporate Insolvencies
10              Corporate Bankruptcies
11                 Corporate Proposals
12    Individual Business Insolvencies
13    Individual Business Bankruptcies
14       Individual Business Proposals
Name: indicator_name, dtype: object

## Fixing date format

In [67]:
import re
from datetime import datetime

month_map = {
    "jan": "01",
    "feb": "02",
    "fév": "02",
    "mar": "03",
    "apr": "04",
    "avr": "04",
    "may": "05",
    "mai": "05",
    "jun": "06",
    "juin": "06",
    "jul": "07",
    "juil": "07",
    "juill": "07",
    "aug": "08",
    "août": "08",
    "sep": "09",
    "sept": "09",
    "oct": "10",
    "nov": "11",
    "dec": "12",
    "déc": "12"
}

def parse_insolvency_date(x):
    if isinstance(x, pd.Timestamp):
        return x.to_period("M").to_timestamp()
    
    if isinstance(x, datetime):
        return pd.to_datetime(x).to_period("M").to_timestamp()
    
    text = str(x).strip().lower()
    
    parsed = pd.to_datetime(text, errors="coerce")
    if pd.notna(parsed):
        return parsed.to_period("M").to_timestamp()
    
    year_match = re.search(r"(19|20)\d{2}", text)
    if not year_match:
        return pd.NaT
    
    year = year_match.group(0)
    
    for key, month_num in month_map.items():
        if key in text:
            return pd.to_datetime(f"{year}-{month_num}-01")
    
    return pd.NaT

In [68]:
insolvency_long["date"] = insolvency_long["date"].apply(parse_insolvency_date)

In [69]:
insolvency_long[insolvency_long["date"].isna()].head()

Empty DataFrame
Columns: [geography, indicator_name, date, value]
Index: []

In [70]:
insolvency_long["value"] = pd.to_numeric(
    insolvency_long["value"],
    errors="coerce"
)

insolvency_long = insolvency_long.dropna(
    subset=["date", "geography", "indicator_name", "value"]
).copy()

      geography                    indicator_name       date   value
0        Canada                Total Insolvencies 1987-01-01  2765.0
1        Canada                Total Bankruptcies 1987-01-01  2722.0
2        Canada                   Total Proposals 1987-01-01    43.0
3        Canada             Consumer Insolvencies 1987-01-01  2060.0
4        Canada             Consumer Bankruptcies 1987-01-01  2037.0
...         ...                               ...        ...     ...
98905   Nunavut            Corporate Bankruptcies 2026-03-01     0.0
98906   Nunavut               Corporate Proposals 2026-03-01     0.0
98907   Nunavut  Individual Business Insolvencies 2026-03-01     0.0
98908   Nunavut  Individual Business Bankruptcies 2026-03-01     0.0
98909   Nunavut     Individual Business Proposals 2026-03-01     0.0

[96705 rows x 4 columns]

In [72]:
consumer_insolvency_canada = insolvency_long[
    (insolvency_long["geography"] == "Canada") &
    (insolvency_long["indicator_name"].str.contains(
        "Consumer Insolvencies",
        case=False,
        na=False
    ))
].copy()

consumer_insolvency_canada = consumer_insolvency_canada.rename(
    columns={
        "value": "consumer_insolvencies"
    }
)

consumer_insolvency_canada = consumer_insolvency_canada[
    [
        "date",
        "geography",
        "consumer_insolvencies"
    ]
].copy()

consumer_insolvency_canada.head()

          date geography  consumer_insolvencies
3   1987-01-01    Canada                 2060.0
213 1987-02-01    Canada                 2185.0
423 1987-03-01    Canada                 2245.0
633 1987-04-01    Canada                 2071.0
843 1987-05-01    Canada                 1884.0

In [73]:
consumer_insolvency_canada["date"] = pd.to_datetime(
    consumer_insolvency_canada["date"]
)

consumer_insolvency_canada["quarter"] = (
    consumer_insolvency_canada["date"]
    .dt.to_period("Q")
    .dt.to_timestamp()
)

consumer_insolvency_q = consumer_insolvency_canada.groupby(
    ["quarter", "geography"],
    as_index=False
)["consumer_insolvencies"].sum()

consumer_insolvency_q = consumer_insolvency_q.rename(
    columns={
        "quarter": "date"
    }
)

consumer_insolvency_q.head()

        date geography  consumer_insolvencies
0 1987-01-01    Canada                 6490.0
1 1987-04-01    Canada                 6164.0
2 1987-07-01    Canada                 5945.0
3 1987-10-01    Canada                 6136.0
4 1988-01-01    Canada                 6784.0

In [74]:
consumer_insolvency_q = consumer_insolvency_q.sort_values(
    ["geography", "date"]
)

consumer_insolvency_q["insolvency_growth_yoy"] = (
    consumer_insolvency_q
    .groupby("geography")["consumer_insolvencies"]
    .pct_change(4) * 100
)

consumer_insolvency_q.tail()

          date geography  consumer_insolvencies  insolvency_growth_yoy
152 2025-01-01    Canada                34225.0               1.003394
153 2025-04-01    Canada                35114.0               0.091215
154 2025-07-01    Canada                36256.0               4.822482
155 2025-10-01    Canada                34862.0               3.325430
156 2026-01-01    Canada                37121.0               8.461651

In [75]:
dashboard_canada_with_insolvency = dashboard_canada.merge(
    consumer_insolvency_q,
    on=["date", "geography"],
    how="left"
)

dashboard_canada_with_insolvency.tail()

,date,geography,debt_service_ratio,debt_service_ratio_interest_only,disposable_income,household_income,mortgage_debt_payments,mortgage_debt_service_ratio,mortgage_debt_service_ratio_interest_only,mortgage_interest_paid,...,interest_cost_change_yoy,dsr_score,debt_income_score,interest_pressure_score,income_pressure_score,risk_score,risk_category,suggested_action,consumer_insolvencies,insolvency_growth_yoy
139,2024-10-01,Canada,14.67,8.80,1765468.0,2708228.0,152772.0,7.89,5.21,100780.0,...,-0.03,65,65,20.0,20.0,49.25,Moderate Risk,Increase monitoring of household credit stress...,33740.0,6.057272
140,2025-01-01,Canada,14.66,8.70,1780588.0,2724352.0,153412.0,7.87,5.18,100948.0,...,-0.08,65,45,20.0,20.0,43.25,Moderate Risk,Increase monitoring of household credit stress...,34225.0,1.003394
141,2025-04-01,Canada,14.70,8.70,1788440.0,2733832.0,154352.0,7.88,5.17,101248.0,...,-0.11,65,65,20.0,20.0,49.25,Moderate Risk,Increase monitoring of household credit stress...,35114.0,0.091215
142,2025-07-01,Canada,14.61,8.54,1807932.0,2766612.0,154324.0,7.81,5.08,100336.0,...,-0.11,65,65,20.0,45.0,53.00,Moderate Risk,Increase monitoring of household credit stress...,36256.0,4.822482
143,2025-10-01,Canada,14.57,8.46,1818456.0,2783776.0,154284.0,7.77,5.02,99772.0,...,-0.08,65,65,20.0,45.0,53.00,Moderate Risk,Increase monitoring of household credit stress...,34862.0,3.325430

In [76]:
def score_insolvency_growth(x):
    if pd.isna(x):
        return np.nan
    if x < 0:
        return 20
    elif x < 5:
        return 45
    elif x < 15:
        return 65
    else:
        return 85

In [77]:
dashboard_canada_with_insolvency["insolvency_score"] = (
    dashboard_canada_with_insolvency["insolvency_growth_yoy"]
    .apply(score_insolvency_growth)
)

In [78]:
dashboard_canada_with_insolvency["risk_score_final"] = (
    dashboard_canada_with_insolvency["dsr_score"] * 0.30 +
    dashboard_canada_with_insolvency["debt_income_score"] * 0.25 +
    dashboard_canada_with_insolvency["insolvency_score"] * 0.20 +
    dashboard_canada_with_insolvency["interest_pressure_score"] * 0.15 +
    dashboard_canada_with_insolvency["income_pressure_score"] * 0.10
)

In [79]:
dashboard_canada_with_insolvency["risk_category_final"] = (
    dashboard_canada_with_insolvency["risk_score_final"]
    .apply(assign_risk_category)
)

dashboard_canada_with_insolvency["suggested_action_final"] = (
    dashboard_canada_with_insolvency["risk_category_final"]
    .apply(assign_suggested_action)
)

In [80]:
dashboard_canada_with_insolvency.to_csv(
    PROCESSED_DIR / "dashboard_ready_canada_credit_risk_final.csv",
    index=False
)

In [81]:
dashboard_canada_with_insolvency[
    dashboard_canada_with_insolvency["risk_score_final"].notna()
].tail(10)[
    [
        "date",
        "geography",
        "debt_service_ratio",
        "debt_to_disposable_income",
        "consumer_insolvencies",
        "insolvency_growth_yoy",
        "risk_score_final",
        "risk_category_final",
        "suggested_action_final"
    ]
]

,date,geography,debt_service_ratio,debt_to_disposable_income,consumer_insolvencies,insolvency_growth_yoy,risk_score_final,risk_category_final,suggested_action_final
134,2023-07-01,Canada,15.09,184.41,30471.0,17.830626,70.50,Elevated Risk,Review vulnerable borrower segments and stress...
135,2023-10-01,Canada,15.13,182.98,31813.0,22.901294,67.50,Elevated Risk,Review vulnerable borrower segments and stress...
136,2024-01-01,Canada,15.10,180.08,33885.0,13.994954,63.50,Elevated Risk,Review vulnerable borrower segments and stress...
137,2024-04-01,Canada,15.09,179.10,35082.0,12.355880,63.50,Elevated Risk,Review vulnerable borrower segments and stress...
138,2024-07-01,Canada,14.77,178.19,34588.0,13.511207,57.50,Moderate Risk,Increase monitoring of household credit stress...
139,2024-10-01,Canada,14.67,177.20,33740.0,6.057272,53.75,Moderate Risk,Increase monitoring of household credit stress...
140,2025-01-01,Canada,14.66,174.90,34225.0,1.003394,44.75,Moderate Risk,Increase monitoring of household credit stress...
141,2025-04-01,Canada,14.70,175.87,35114.0,0.091215,49.75,Moderate Risk,Increase monitoring of household credit stress...
142,2025-07-01,Canada,14.61,176.66,36256.0,4.822482,52.25,Moderate Risk,Increase monitoring of household credit stress...
143,2025-10-01,Canada,14.57,176.85,34862.0,3.325430,52.25,Moderate Risk,Increase monitoring of household credit stress...

In [82]:
print(dashboard_canada_with_insolvency.shape)
print(dashboard_canada_with_insolvency["date"].min())
print(dashboard_canada_with_insolvency["date"].max())
print(dashboard_canada_with_insolvency["consumer_insolvencies"].notna().sum())

(144, 47)
1990-01-01 00:00:00
2025-10-01 00:00:00
144